### ISSUE TITLE
It appears upon starting

### ISSUE THREAD

**Issue by hussam-dh** [ehrishirajsharma/SwiftnessX#12]
Checking for update
Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/ehrishirajsharma/SwiftnessX/releases/latest), please ensure a production release exists: SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.this (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:235:1)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at t.CancellationToken.this [as createPromise] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/CancellationToken.js:89:1)
    at t.ElectronHttpExecutor.doApiRequest (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:151:10)
    at t.ElectronHttpExecutor.options (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:144:25)
    at t.GitHubProvider.this [as httpRequest] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/Provider.js:69:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:188:1
    at Generator.next (<anonymous>)
From previous event:
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
From previous event:
    at t.GitHubProvider.options [as getLatestVersion] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfo (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
    at JSON.parse (<anonymous>)
    at IncomingMessage.this (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:235:1)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at t.CancellationToken.this [as createPromise] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/CancellationToken.js:89:1)
    at t.ElectronHttpExecutor.doApiRequest (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:151:10)
    at t.ElectronHttpExecutor.options (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:144:25)
    at t.GitHubProvider.this [as httpRequest] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/Provider.js:69:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:188:1
    at Generator.next (<anonymous>)
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
    at t.GitHubProvider.options [as getLatestVersion] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.getUpdateInfo (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
    at get (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/index.js:10:1)
    at url (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:190:95)
    at Generator.throw (<anonymous>)
From previous event:
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
From previous event:
    at t.GitHubProvider.options [as getLatestVersion] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfo (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7),
XML:
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:https://github.com/ehrishirajsharma/SwiftnessX/releases</id>
  <link type="text/html" rel="alternate" href="https://github.com/ehrishirajsharma/SwiftnessX/releases"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/ehrishirajsharma/SwiftnessX/releases.atom"/>
  <title>Release notes from SwiftnessX</title>
  <updated>2018-11-07T09:18:02Z</updated>
  <entry>
    <id>tag:github.com,2008:Repository/155306479/v0.1.0</id>
    <updated>2018-11-07T14:39:12Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/ehrishirajsharma/SwiftnessX/releases/tag/v0.1.0"/>
    <title>0.1.0</title>
    <content type="html">&lt;p&gt;Initial version of SwiftnessX with:&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;checklist&lt;/li&gt;
&lt;li&gt;payloads&lt;/li&gt;
&lt;li&gt;export &amp;amp; import&lt;/li&gt;
&lt;/ul&gt;</content>
    <author>
      <name>TomasBaskys</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars1.githubusercontent.com/u/5922899?s=60&amp;v=4"/>
  </entry>
</feed>

    at JSON.parse (<anonymous>)
    at IncomingMessage.this (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:235:1)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at t.CancellationToken.this [as createPromise] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/CancellationToken.js:89:1)
    at t.ElectronHttpExecutor.doApiRequest (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:151:10)
    at t.ElectronHttpExecutor.options (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:144:25)
    at t.GitHubProvider.this [as httpRequest] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/Provider.js:69:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:188:1
    at Generator.next (<anonymous>)
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
    at t.GitHubProvider.options [as getLatestVersion] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.getUpdateInfo (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
    at JSON.parse (<anonymous>)
    at IncomingMessage.this (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:235:1)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at t.CancellationToken.this [as createPromise] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/CancellationToken.js:89:1)
    at t.ElectronHttpExecutor.doApiRequest (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:151:10)
    at t.ElectronHttpExecutor.options (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/httpExecutor.js:144:25)
    at t.GitHubProvider.this [as httpRequest] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/Provider.js:69:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:188:1
    at Generator.next (<anonymous>)
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
    at t.GitHubProvider.options [as getLatestVersion] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.getUpdateInfo (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
    at get (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/index.js:10:1)
    at url (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:190:95)
    at Generator.throw (<anonymous>)
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
    at t.GitHubProvider.options [as getLatestVersion] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.getUpdateInfo (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7),
    at get (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/builder-util-runtime/out/index.js:10:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:128:122
    at Generator.throw (<anonymous>)
From previous event:
    at t.GitHubProvider.options [as getLatestVersion] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfo (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/tmp/.mount_swiftnlLftWX/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)

it looks like it happens at startup when printing checking or update

Regards

**Comment by ehrishirajsharma** [comment]
Can you also point out your OS and Node version?

**Comment by ehrishirajsharma** [comment]
Closing because of no updates..feel free to reopen if you or anybody encounter this again.

**Comment by hussam-dh** [comment]
So Sorry,
OS: Fedora 25 64bit
Node: v10.6.0

**Comment by ehrishirajsharma** [comment]
I will test it on Fedora this weekend and update you on this.

**Comment by ehrishirajsharma** [comment]
Hi @hussam-dh, 

Please re-test it with the latest release.

**Comment by hussam-dh** [comment]
will do,
thank you very much
