### ISSUE TITLE
Blanc screen when opening the application

### ISSUE THREAD

**Issue by vincentcox** [ehrishirajsharma/SwiftnessX#31]
**Operating System**
Ubuntu 18.04

**Describe the bug**
When opening the application, it doesn't show any content. When clicking on "open", nothing happens. 

**To Reproduce**
1. Install the .deb release file on Ubuntu 18.04 with dpkg. 
1. Open the app

**Expected behavior**
Properly open the application. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9286611/56117357-2e53eb80-5f68-11e9-99eb-b6b01356294d.png)

**Additional logs**
```
┌─[vincent@usbstick]─[~/]
└──╼ $swiftness 

(swiftness:26619): Gtk-WARNING **: 10:21:36.183: Theme parsing error: gtk.css:11546:3: '/*' in comment block

(swiftness:26619): Gtk-WARNING **: 10:21:36.183: Theme parsing error: gtk.css:11652:2: '/*' in comment block
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Swiftness/resources/app-update.yml'
    at coroutine (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:607:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.provider [as loadUpdateConfig] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:608:1)
    at t.Lazy.error (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:225:1)
    at t.Lazy../node_modules/lockfile/lockfile.js [as value] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/lazy-val/out/main.js:22:1)
    at stagingUserIdPromise (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:507:1)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfo (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/opt/Swiftness/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
```

**Comment by ehrishirajsharma** [comment]
Hi @vincentcox, 

We just tried to reproduce this with fresh install of Ubuntu 18.04; app was working as expected.

Do you also have SwiftnessX's older version installed on your system? One more thing, did the app behave same with Appimage?

**If SwiftnessX's older version is installed:**

1. Open the app
2. Export your data
3. Now remove the app's storage.json
4. Remove the older version
5. Reinstall latest version
6. Import the data (which you exported in 2nd step)

Let me know if that works.

**Comment by vincentcox** [comment]
Hi @ehrishirajsharma ,

It appears that the error is caused because the program couldn't find the file `/opt/Swiftness/resources/app-update.yml`. From the releases I downloaded the SwiftnessX.zip file, copied the contents of resources to the `/opt/Swiftness` to try to fix this:

```
sudo cp -r ~/Downloads/SwiftnessX.app/Contents/Resources/* /opt/Swiftness/resources/
```

Now, when I try to launch the application, it throws this error:

```
└──╼ $swiftness

(swiftness:23264): Gtk-WARNING **: 13:14:44.511: Theme parsing error: gtk.css:11546:3: '/*' in comment block

(swiftness:23264): Gtk-WARNING **: 13:14:44.511: Theme parsing error: gtk.css:11652:2: '/*' in comment block
Checking for update
Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/ehrishirajsharma/SwiftnessX/releases/latest), please ensure a production release exists: SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.this (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:235:1)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at t.CancellationToken.this [as createPromise] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/CancellationToken.js:89:1)
    at t.ElectronHttpExecutor.doApiRequest (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:151:10)
    at t.ElectronHttpExecutor.options (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:144:25)
    at t.GitHubProvider.this [as httpRequest] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/Provider.js:69:1)
    at /opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:188:1
    at Generator.next (<anonymous>)
From previous event:
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
From previous event:
    at t.GitHubProvider.options [as getLatestVersion] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.getUpdateInfo (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/opt/Swiftness/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
    at JSON.parse (<anonymous>)
    at IncomingMessage.this (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:235:1)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at t.CancellationToken.this [as createPromise] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/CancellationToken.js:89:1)
    at t.ElectronHttpExecutor.doApiRequest (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:151:10)
    at t.ElectronHttpExecutor.options (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:144:25)
    at t.GitHubProvider.this [as httpRequest] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/Provider.js:69:1)
    at /opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:188:1
    at Generator.next (<anonymous>)
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
    at t.GitHubProvider.options [as getLatestVersion] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:174:1)
    at /opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.getUpdateInfo (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:519:1)
    at info (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
    at t.AppImageUpdater.asArray [as doCheckForUpdates] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:548:68)
    at e (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    at t.AppImageUpdater.requestHeaders [as _checkForUpdates] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:448:1)
    at t.AppImageUpdater.checkForUpdates (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/AppUpdater.js:358:1)
    at App.r.app.on (/opt/Swiftness/resources/app.asar/webpack:/app/main.dev.js:128:14)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
    at get (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:10:1)
    at url (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:190:95)
    at Generator.throw (<anonymous>)
From previous event:
    at t.GitHubProvider.updateInfo [as getLatestVersionString] (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:199:1)
    at attribute (/opt/Swiftness/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:121:1)
From previous event:
    at t.GitHubProvider.options [as getLatestVersion] 
```

**Comment by vincentcox** [comment]
I also tried the appimage:

![image](https://user-images.githubusercontent.com/9286611/56205645-a85ca100-604a-11e9-85cb-aff758dcc2a8.png)

But this gives the same error.

**Comment by vincentcox** [comment]
This issue is related: https://github.com/ehrishirajsharma/SwiftnessX/issues/12

**Comment by ehrishirajsharma** [comment]
Hi @vincentcox, 

Just wanted to update on this thread, still working on this issue. There seem to be multiple problems with Debian environment. I will keep you posted once I hve more updates.

**Comment by vincentcox** [comment]
Thanks for the update, really kind of you. Take your time. I can test on Kali and Ubuntu for you, let me know how I can help! 💪

**Comment by ehrishirajsharma** [comment]
Hi @vincentcox,

Please confirm with the latest release, let me know if everything works as expected on Ubuntu.

**Comment by vincentcox** [comment]
Unfortunately, on Ubuntu it is still happening:

![image](https://user-images.githubusercontent.com/9286611/58460136-45702680-812d-11e9-948e-4bf5a0ac2f62.png)
